# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-04 03:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=140)),
                ('date', models.DateTimeField()),
                ('description', models.TextField()),
            ],
        ),
    ]
