# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-07 16:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_comment_post'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=140)),
                ('lastName', models.CharField(max_length=140)),
                ('email', models.CharField(max_length=140)),
                ('password', models.CharField(max_length=140)),
            ],
        ),
        migrations.AddField(
            model_name='post',
            name='userP',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='blog.User'),
        ),
    ]
