# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-11 14:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20170510_2207'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('description', models.CharField(blank=True, db_column='Description', max_length=500, null=True)),
                ('date', models.DateField(blank=True, db_column='Date', null=True)),
            ],
            options={
                'db_table': 'comments',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('path', models.CharField(blank=True, db_column='Path', max_length=100, null=True)),
            ],
            options={
                'db_table': 'images',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Posts',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, db_column='Title', max_length=50, null=True)),
                ('description', models.CharField(blank=True, db_column='Description', max_length=200, null=True)),
                ('content', models.CharField(blank=True, db_column='Content', max_length=5000, null=True)),
                ('views', models.IntegerField(blank=True, db_column='Views', null=True)),
                ('date', models.DateField(blank=True, db_column='Date', null=True)),
            ],
            options={
                'db_table': 'posts',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Profilepictures',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('path', models.CharField(blank=True, db_column='Path', max_length=100, null=True)),
            ],
            options={
                'db_table': 'profilepictures',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Stadistics',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('yes', models.IntegerField(blank=True, db_column='Yes', null=True)),
                ('no', models.IntegerField(blank=True, db_column='No', null=True)),
                ('unknown', models.IntegerField(blank=True, db_column='Unknown', null=True)),
            ],
            options={
                'db_table': 'stadistics',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('tag', models.CharField(blank=True, db_column='Tag', max_length=20, null=True)),
            ],
            options={
                'db_table': 'tags',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.IntegerField(db_column='ID', primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, db_column='Name', max_length=75, null=True)),
                ('username', models.CharField(blank=True, db_column='UserName', max_length=25, null=True, unique=True)),
                ('email', models.CharField(blank=True, db_column='Email', max_length=75, null=True, unique=True)),
                ('password', models.CharField(blank=True, db_column='Password', max_length=200, null=True)),
                ('points', models.IntegerField(blank=True, db_column='Points', null=True)),
            ],
            options={
                'db_table': 'users',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Usertypes',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, db_column='Name', max_length=50, null=True)),
            ],
            options={
                'db_table': 'usertypes',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Lawprojects',
            fields=[
                ('fk_post', models.ForeignKey(db_column='FK_Post', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='blog.Posts')),
                ('link', models.CharField(blank=True, db_column='Link', max_length=200, null=True)),
            ],
            options={
                'db_table': 'lawprojects',
                'managed': False,
            },
        ),
    ]
