insert into UserTypes(Name) values ('Administrador');
insert into UserTypes(Name) values ('Cliente');


insert into ProfilePictures(Path) values('home/img/1.png');
insert into ProfilePictures(Path) values('home/img/2.png');
insert into ProfilePictures(Path) values('home/img/3.png');
insert into ProfilePictures(Path) values('home/img/4.png');
insert into ProfilePictures(Path) values('home/img/5.png');
insert into ProfilePictures(Path) values('home/img/6.png');
insert into ProfilePictures(Path) values('home/img/7.png');
insert into ProfilePictures(Path) values('home/img/8.png');
insert into ProfilePictures(Path) values('home/img/9.png');
insert into ProfilePictures(Path) values('home/img/10.png');
insert into ProfilePictures(Path) values('home/img/11.png');
insert into ProfilePictures(Path) values('home/img/12.png');
insert into ProfilePictures(Path) values('home/img/13.png');
insert into ProfilePictures(Path) values('home/img/14.png');
insert into ProfilePictures(Path) values('home/img/15.png');
insert into ProfilePictures(Path) values('home/img/16.png');
insert into ProfilePictures(Path) values('home/img/17.png');
insert into ProfilePictures(Path) values('home/img/18.png');
insert into ProfilePictures(Path) values('home/img/19.png');
insert into ProfilePictures(Path) values('home/img/20.png');
insert into ProfilePictures(Path) values('home/img/21.png');
insert into ProfilePictures(Path) values('home/img/22.png');
insert into ProfilePictures(Path) values('home/img/23.png');
insert into ProfilePictures(Path) values('home/img/24.png');
insert into ProfilePictures(Path) values('home/img/25.png');
insert into ProfilePictures(Path) values('home/img/26.png');
insert into ProfilePictures(Path) values('home/img/27.png');
insert into ProfilePictures(Path) values('home/img/28.png');
insert into ProfilePictures(Path) values('home/img/29.png');
insert into ProfilePictures(Path) values('home/img/30.png');
insert into ProfilePictures(Path) values('home/img/31.png');
insert into ProfilePictures(Path) values('home/img/32.png');
insert into ProfilePictures(Path) values('home/img/33.png');
insert into ProfilePictures(Path) values('home/img/34.png');
insert into ProfilePictures(Path) values('home/img/35.png');
insert into ProfilePictures(Path) values('home/img/36.png');
insert into ProfilePictures(Path) values('home/img/37.png');
insert into ProfilePictures(Path) values('home/img/38.png');
insert into ProfilePictures(Path) values('home/img/39.png');
insert into ProfilePictures(Path) values('home/img/40.png');
insert into ProfilePictures(Path) values('home/img/41.png');
insert into ProfilePictures(Path) values('home/img/42.png');
insert into ProfilePictures(Path) values('home/img/43.png');
insert into ProfilePictures(Path) values('home/img/44.png');
insert into ProfilePictures(Path) values('home/img/45.png');
insert into ProfilePictures(Path) values('home/img/46.png');
insert into ProfilePictures(Path) values('home/img/47.png');
insert into ProfilePictures(Path) values('home/img/48.png');
insert into ProfilePictures(Path) values('home/img/49.png');
insert into ProfilePictures(Path) values('home/img/50.png');
insert into ProfilePictures(Path) values('home/img/51.png');
insert into ProfilePictures(Path) values('home/img/52.png');
insert into ProfilePictures(Path) values('home/img/53.png');
insert into ProfilePictures(Path) values('home/img/54.png');
insert into ProfilePictures(Path) values('home/img/55.png');
insert into ProfilePictures(Path) values('home/img/56.png');
insert into ProfilePictures(Path) values('home/img/57.png');
insert into ProfilePictures(Path) values('home/img/58.png');
insert into ProfilePictures(Path) values('home/img/59.png');
insert into ProfilePictures(Path) values('home/img/60.png');
insert into ProfilePictures(Path) values('home/img/61.png');
insert into ProfilePictures(Path) values('home/img/62.png');
insert into ProfilePictures(Path) values('home/img/63.png');
insert into ProfilePictures(Path) values('home/img/64.png');
insert into ProfilePictures(Path) values('home/img/65.png');
insert into ProfilePictures(Path) values('home/img/66.png');
insert into ProfilePictures(Path) values('home/img/67.png');
insert into ProfilePictures(Path) values('home/img/68.png');
insert into ProfilePictures(Path) values('home/img/69.png');
insert into ProfilePictures(Path) values('home/img/70.png');
insert into ProfilePictures(Path) values('home/img/71.png');
insert into ProfilePictures(Path) values('home/img/72.png');
insert into ProfilePictures(Path) values('home/img/73.png');
insert into ProfilePictures(Path) values('home/img/74.png');
insert into ProfilePictures(Path) values('home/img/75.png');
insert into ProfilePictures(Path) values('home/img/76.png');
insert into ProfilePictures(Path) values('home/img/77.png');
insert into ProfilePictures(Path) values('home/img/78.png');
insert into ProfilePictures(Path) values('home/img/79.png');
insert into ProfilePictures(Path) values('home/img/80.png');
insert into ProfilePictures(Path) values('home/img/81.png');
insert into ProfilePictures(Path) values('home/img/82.png');
insert into ProfilePictures(Path) values('home/img/83.png');
insert into ProfilePictures(Path) values('home/img/84.png');
insert into ProfilePictures(Path) values('home/img/85.png');
insert into ProfilePictures(Path) values('home/img/86.png');
insert into ProfilePictures(Path) values('home/img/87.png');
insert into ProfilePictures(Path) values('home/img/88.png');
insert into ProfilePictures(Path) values('home/img/89.png');
insert into ProfilePictures(Path) values('home/img/90.png');
insert into ProfilePictures(Path) values('home/img/91.png');
insert into ProfilePictures(Path) values('home/img/92.png');
insert into ProfilePictures(Path) values('home/img/93.png');
insert into ProfilePictures(Path) values('home/img/94.png');
insert into ProfilePictures(Path) values('home/img/95.png');
insert into ProfilePictures(Path) values('home/img/96.png');
insert into ProfilePictures(Path) values('home/img/97.png');
insert into ProfilePictures(Path) values('home/img/98.png');
insert into ProfilePictures(Path) values('home/img/99.png');
insert into ProfilePictures(Path) values('home/img/100.png');


insert into Users(ID, Name, UserName, Email, PassWord, Points, FK_UserType, FK_ProfilePicture) 
values(1, 'Dylan', 'dylanrodbar', 'dylanrodbar97@gmail.com', '1', 0, 2, 1)
insert into Users(ID, Name, UserName, Email, PassWord, Points, FK_UserType, FK_ProfilePicture) 
values(2, 'Alberto', 'albertorodbar', 'albertorodbar97@gmail.com', '2', 0, 1, 1)

