# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-27 20:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='tabla1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField()),
                ('letra', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='tabla2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero2', models.IntegerField()),
                ('letra2', models.CharField(max_length=20)),
            ],
        ),
    ]
