# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-28 04:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appeGov', '0002_auto_20170427_1534'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='tabla1',
            table='tabla1',
        ),
        migrations.AlterModelTable(
            name='tabla2',
            table='tabla2',
        ),
    ]
